import type { Place, Review } from "./domain";

export const samplePlaces: Place[] = [
  {
    id: "sample-1",
    name: "성수 손칼국수",
    address: "서울 성동구 성수이로 10",
    latitude: 37.5446,
    longitude: 127.0558,
    categoryId: "budget",
    tagIds: ["large", "waiting"],
    ownerAnonymousId: "sample",
    status: "public",
    heroImageUrl:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-05-01T09:00:00.000Z",
    reviewCount: 2,
    averageRevisitScore: 0.9,
  },
  {
    id: "sample-2",
    name: "부산 돼지국밥",
    address: "부산 부산진구 중앙대로 1",
    latitude: 35.1578,
    longitude: 129.0592,
    categoryId: "local",
    tagIds: ["late", "large"],
    ownerAnonymousId: "sample",
    status: "public",
    heroImageUrl:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-05-03T09:00:00.000Z",
    reviewCount: 1,
    averageRevisitScore: 1,
  },
  {
    id: "sample-3",
    name: "제주 바다카페",
    address: "제주 제주시 탑동로 20",
    latitude: 33.5172,
    longitude: 126.526,
    categoryId: "cafe",
    tagIds: ["quiet", "parking"],
    ownerAnonymousId: "sample",
    status: "public",
    heroImageUrl:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    createdAt: "2026-05-06T09:00:00.000Z",
    reviewCount: 1,
    averageRevisitScore: 0.6,
  },
];

export const sampleReviews: Review[] = [
  {
    id: "review-1",
    placeId: "sample-1",
    nickname: "든든한 김치탐험가",
    priceRange: "1만원 이하",
    recommendedMenu: "바지락 칼국수",
    goodPoint: "국물이 깔끔하고 양이 많아서 점심 한 끼로 충분했어요.",
    badPoint: "점심시간에는 줄이 길어서 15분 정도 기다렸습니다.",
    revisitIntent: "yes",
    ownerAnonymousId: "sample",
    status: "public",
    createdAt: "2026-05-07T09:00:00.000Z",
  },
  {
    id: "review-2",
    placeId: "sample-1",
    nickname: "야무진 반찬연구원",
    priceRange: "1만-2만원",
    recommendedMenu: "칼만두",
    goodPoint: "김치가 시원하고 테이블 회전이 빨랐습니다.",
    badPoint: "매장이 넓지는 않아서 조용한 분위기는 아니에요.",
    revisitIntent: "maybe",
    ownerAnonymousId: "sample",
    status: "public",
    createdAt: "2026-05-08T09:00:00.000Z",
  },
  {
    id: "review-3",
    placeId: "sample-2",
    nickname: "솔직한 국밥친구",
    priceRange: "1만원 이하",
    recommendedMenu: "따로국밥",
    goodPoint: "국물이 진하고 새벽에도 든든하게 먹기 좋았습니다.",
    badPoint: "간이 조금 센 편이라 맑은 국물을 좋아하면 호불호가 있을 수 있어요.",
    revisitIntent: "yes",
    ownerAnonymousId: "sample",
    status: "public",
    createdAt: "2026-05-09T09:00:00.000Z",
  },
  {
    id: "review-4",
    placeId: "sample-3",
    nickname: "담백한 디저트산책러",
    priceRange: "1만-2만원",
    recommendedMenu: "당근 케이크",
    goodPoint: "창가 자리에서 바다가 보여서 쉬어가기 좋았습니다.",
    badPoint: "주말 오후에는 좌석 경쟁이 조금 있습니다.",
    revisitIntent: "maybe",
    ownerAnonymousId: "sample",
    status: "public",
    createdAt: "2026-05-10T09:00:00.000Z",
  },
];
